/* tslint:disable */
/* eslint-disable */
/**
 * Own World Admin API specifications
 * A specification that describes API interfaces for admin API of OW project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

